---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - limitranges
  - resourcequotas
  - serviceaccounts
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - platform.ellery.dev
  resources:
  - previewenvironments
  verbs:
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - platform.ellery.dev
  resources:
  - previewenvironments/finalizers
  verbs:
  - update
- apiGroups:
  - platform.ellery.dev
  resources:
  - previewenvironments/status
  verbs:
  - get
  - patch
  - update
