apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../observability
patches:
- target:
    kind: Deployment
    name: preview-environment-controller-controller-manager
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --argo-namespace=argocd
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --argo-project=preview-environments
