apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: preview-application-manager
  namespace: argocd
rules:
- apiGroups: [argoproj.io]
  resources: [applications]
  verbs: [get, list, watch, create, patch, delete]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: preview-application-manager
  namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: preview-application-manager
subjects:
- kind: ServiceAccount
  name: preview-environment-controller-controller-manager
  namespace: preview-environment-controller-system
